language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

node_js:
  - "10"

services:
  - redis-server

install:
  - npm install
  - npm run build
  - pip install -r requirements.txt

script:
  - python -m pytest