name: mxcube3
dependencies:
  - python=3.7
  - gevent
  - flask
  - flask-socketio
  - gevent-websocket
  - redis-py
  - scipy
  - mock
  - jsonpickle
  - pillow
  - suds-jurko
  - python-ldap
  - lxml
  - numpy
  - requests
  - scandir
  - redis
  - nodejs
  - ffmpeg
  - pytango
  - opencv

  - pip:
      - Flask-Session
      - git+https://github.com/marcus-oscarsson/python-v4l2.git
      - Louie-latest
      - gipc
