# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import argus_service_pb2 as argus__service__pb2


class SpawnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartProcesses = channel.unary_unary(
            "/argussight.SpawnerService/StartProcesses",
            request_serializer=argus__service__pb2.StartProcessesRequest.SerializeToString,
            response_deserializer=argus__service__pb2.StartProcessesResponse.FromString,
        )
        self.TerminateProcesses = channel.unary_unary(
            "/argussight.SpawnerService/TerminateProcesses",
            request_serializer=argus__service__pb2.TerminateProcessesRequest.SerializeToString,
            response_deserializer=argus__service__pb2.TerminateProcessesResponse.FromString,
        )
        self.ManageProcesses = channel.unary_unary(
            "/argussight.SpawnerService/ManageProcesses",
            request_serializer=argus__service__pb2.ManageProcessesRequest.SerializeToString,
            response_deserializer=argus__service__pb2.ManageProcessesResponse.FromString,
        )
        self.GetProcesses = channel.unary_unary(
            "/argussight.SpawnerService/GetProcesses",
            request_serializer=argus__service__pb2.GetProcessesRequest.SerializeToString,
            response_deserializer=argus__service__pb2.GetProcessesResponse.FromString,
        )
        self.ChangeSettings = channel.unary_unary(
            "/argussight.SpawnerService/ChangeSettings",
            request_serializer=argus__service__pb2.ChangeSettingsRequest.SerializeToString,
            response_deserializer=argus__service__pb2.ChangeSettingsResponse.FromString,
        )
        self.AddStream = channel.unary_unary(
            "/argussight.SpawnerService/AddStream",
            request_serializer=argus__service__pb2.AddStreamRequest.SerializeToString,
            response_deserializer=argus__service__pb2.AddStreamResponse.FromString,
        )
        self.RemoveStream = channel.unary_unary(
            "/argussight.SpawnerService/RemoveStream",
            request_serializer=argus__service__pb2.RemoveStreamRequest.SerializeToString,
            response_deserializer=argus__service__pb2.RemoveStreamResponse.FromString,
        )
        self.HideStream = channel.unary_unary(
            "/argussight.SpawnerService/HideStream",
            request_serializer=argus__service__pb2.HideStreamRequest.SerializeToString,
            response_deserializer=argus__service__pb2.HideStreamResponse.FromString,
        )
        self.ShowStream = channel.unary_unary(
            "/argussight.SpawnerService/ShowStream",
            request_serializer=argus__service__pb2.ShowStreamRequest.SerializeToString,
            response_deserializer=argus__service__pb2.ShowStreamResponse.FromString,
        )


class SpawnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TerminateProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ManageProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChangeSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HideStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ShowStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpawnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartProcesses": grpc.unary_unary_rpc_method_handler(
            servicer.StartProcesses,
            request_deserializer=argus__service__pb2.StartProcessesRequest.FromString,
            response_serializer=argus__service__pb2.StartProcessesResponse.SerializeToString,
        ),
        "TerminateProcesses": grpc.unary_unary_rpc_method_handler(
            servicer.TerminateProcesses,
            request_deserializer=argus__service__pb2.TerminateProcessesRequest.FromString,
            response_serializer=argus__service__pb2.TerminateProcessesResponse.SerializeToString,
        ),
        "ManageProcesses": grpc.unary_unary_rpc_method_handler(
            servicer.ManageProcesses,
            request_deserializer=argus__service__pb2.ManageProcessesRequest.FromString,
            response_serializer=argus__service__pb2.ManageProcessesResponse.SerializeToString,
        ),
        "GetProcesses": grpc.unary_unary_rpc_method_handler(
            servicer.GetProcesses,
            request_deserializer=argus__service__pb2.GetProcessesRequest.FromString,
            response_serializer=argus__service__pb2.GetProcessesResponse.SerializeToString,
        ),
        "ChangeSettings": grpc.unary_unary_rpc_method_handler(
            servicer.ChangeSettings,
            request_deserializer=argus__service__pb2.ChangeSettingsRequest.FromString,
            response_serializer=argus__service__pb2.ChangeSettingsResponse.SerializeToString,
        ),
        "AddStream": grpc.unary_unary_rpc_method_handler(
            servicer.AddStream,
            request_deserializer=argus__service__pb2.AddStreamRequest.FromString,
            response_serializer=argus__service__pb2.AddStreamResponse.SerializeToString,
        ),
        "RemoveStream": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveStream,
            request_deserializer=argus__service__pb2.RemoveStreamRequest.FromString,
            response_serializer=argus__service__pb2.RemoveStreamResponse.SerializeToString,
        ),
        "HideStream": grpc.unary_unary_rpc_method_handler(
            servicer.HideStream,
            request_deserializer=argus__service__pb2.HideStreamRequest.FromString,
            response_serializer=argus__service__pb2.HideStreamResponse.SerializeToString,
        ),
        "ShowStream": grpc.unary_unary_rpc_method_handler(
            servicer.ShowStream,
            request_deserializer=argus__service__pb2.ShowStreamRequest.FromString,
            response_serializer=argus__service__pb2.ShowStreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "argussight.SpawnerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SpawnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartProcesses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/StartProcesses",
            argus__service__pb2.StartProcessesRequest.SerializeToString,
            argus__service__pb2.StartProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TerminateProcesses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/TerminateProcesses",
            argus__service__pb2.TerminateProcessesRequest.SerializeToString,
            argus__service__pb2.TerminateProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ManageProcesses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/ManageProcesses",
            argus__service__pb2.ManageProcessesRequest.SerializeToString,
            argus__service__pb2.ManageProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetProcesses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/GetProcesses",
            argus__service__pb2.GetProcessesRequest.SerializeToString,
            argus__service__pb2.GetProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ChangeSettings(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/ChangeSettings",
            argus__service__pb2.ChangeSettingsRequest.SerializeToString,
            argus__service__pb2.ChangeSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/AddStream",
            argus__service__pb2.AddStreamRequest.SerializeToString,
            argus__service__pb2.AddStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RemoveStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/RemoveStream",
            argus__service__pb2.RemoveStreamRequest.SerializeToString,
            argus__service__pb2.RemoveStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def HideStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/HideStream",
            argus__service__pb2.HideStreamRequest.SerializeToString,
            argus__service__pb2.HideStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ShowStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/argussight.SpawnerService/ShowStream",
            argus__service__pb2.ShowStreamRequest.SerializeToString,
            argus__service__pb2.ShowStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
